version: "3.8"
services:
  database:
    container_name: "databasegeoapi"
    image: "postgis/postgis"
    ports: 
      - "5432:5432"
    volumes:
      - db_geoapi_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass 
      POSTGRES_DB: geoapidb

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_geoapi_data: {}
  pgadmin_data: {}

